### ISSUE TITLE
Could not convert string to float

### ISSUE THREAD

**Issue by c0olix** [pacificweb/python-noise-detection#1]
Hello there,

on trying your python script I am getting an Error:

 $ sudo ~/soundcapture.py
arecord: main:788: audio open error: No such file or directory

Traceback (most recent call last):
  File "/home/pi/soundcapture.py", line 37, in <module>
    sys.exit(main(sys.argv[1:]) or 0)
  File "/home/pi/soundcapture.py", line 24, in main
    amplitude = float(result)
ValueError: could not convert string to float:

As I am not familiar your script, sox or python, I am wondering if I am doing sth wrong or if there is a bug.

regards,

Janek

**Comment by pacificweb** [comment]
Hi Janek, 
The error is from the arecord application.
Take a look in sox.sh script you have tout find the correct arecord switches according you audio setup

**Comment by leonardosampaio** [comment]
Got ride of this error adding this to the end of line 7 in sox.sh: -D sysdefault:CARD=1

**Comment by pacificweb** [comment]
Excellent!
